# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.4.2
_src_path: gh:algorandfoundation/algokit-python-template
author_email: javoxdaemon@gmail.com
author_name: javier_varon
contract_name: digitalmarketplace
deployment_language: python
preset_name: production
project_name: digital_marketplace

